config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    get :ranking, on: :collection
    get :search, on: :collection
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get :likes, on: :member
  end
  resources :messages, only: :create
  resources :rooms, only: [:index, :create, :show]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params.merge(user_id: current_user.id, post_id: params[:post_id]))
    user = comment.user
    comment_count = Post.find(params[:post_id]).comments.count
    render json:{comment: comment, user: user, comment_count: comment_count}
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= link_to comment.user.nickname, user_path(@post.user.id), class:"comment-username" %> 
<span><%= comment.text%><span>
<% if user_signed_in? && current_user.id == comment.user.id %>
  <%= link_to(post_comment_path(comment.post.id, comment.id), method: :delete, class:"fa fa-trash fa-1x trash-btn-comment", remote: true, name:comment.id ) do%>
  <% end %>
<% end %>