config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    get :ranking, on: :collection
    get :search, on: :collection
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get :likes, on: :member
  end
  resources :messages, only: :create
  resources :rooms, only: [:index, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '洗顔料'},
    {id: 3, name: 'クレンジング'},
    {id: 4, name: '化粧水'},
    {id: 5, name: '乳液、美容液'},
    {id: 6, name: 'フェイスクリーム'},
    {id: 7, name: '日焼け対策、UVケア'},
    {id: 8, name: 'ベースメイク'},
    {id: 9, name: '香水、フレグランス'},
    {id: 10, name: 'ヘアケア、スタイリング'},
    {id: 11, name: '美容グッズ、美容家電'},
    {id: 12, name: 'サプリメント、フード'},
    {id: 13, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    # {id: 1, name: '---'},
    {id: 2, name: '男性'},
    {id: 3, name: '女性'}
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :caption
    validates :image
    validates :category_id, numericality: {other_than: 1, message: "を選択してください"}
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

  has_many :posts
  has_many :comments
  has_many :likes
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :message, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  

  with_options presence: true do
    validates :nickname
    validates :age, format: {with: /\A[0-9]{2,3}\z/, message: "は半角数字で入力してください"}
    validates :gender_id
  end
  validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は6文字以上、半角英数混合で入力してください"}
  
  def liked_by?(post)
    self.likes.exists?(post_id: post.id)
  end

  def followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def destroy
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
  end

  private 
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :back_index, only: :edit
  before_action :search_item_category

  def index
    @posts = Post.order("created_at DESC").page(params[:page]).per(9)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy 
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    @posts = @p.result.order("created_at DESC").page(params[:page]).per(2)
    category_id = params[:q][:category_id_eq]
    @category = Category.find_by(id: category_id)
  end

  def ranking
    @posts = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
  
  private 
  def post_params
    params.require(:post).permit(:image,:caption,:category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def back_index
    if current_user.id != @post.user_id
      redirect_to root_path
    end
  end

  def search_item_category
    @p = Post.ransack(params[:q])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.joins(:entries).merge(Entry.where(room: current_user.rooms).where.not(user: current_user))
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(entry_params.merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def entry_params
    params.require(:entry).permit(:user_id, :room_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry_room, only: [:show, :likes]

  def show
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(9)
  end

  def likes
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.where(id: likes).order("created_at DESC").page(params[:page]).per(9)
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def set_entry_room
    @user = User.find(params[:id])
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id then
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <%= link_to post.user.nickname, user_path(post.user.id), class:"user-name-post" %>
  <% if current_user.liked_by?(post) %>
    <%= link_to post_likes_path(post.id),method: :delete,remote: true do %> 
      <i class="fa fa-heart unlike-btn fa-2x"></i> 
    <% end %> 
  <% else %> 
    <%= link_to post_likes_path(post.id),method: :post,remote: true do %> 
     <i class="fa fa-heart like-btn fa-2x"></i> 
    <% end %> 
  <% end %> 
    <% if post.likes.count != 0 %> 
      <span><%= "#{post.likes.count}いいね!" %></span> 
    <% end %>
<% else %>
  <%= link_to post.user.nickname, user_path(post.user.id), class:"user-name-post" %>
  <% if post.user.liked_by?(post) %>
    <%= link_to post_likes_path(post.id),method: :delete,remote: true do %> 
      <i class="fa fa-heart unlike-btn fa-2x"></i> 
    <% end %> 
  <% else %>
    <%= link_to post_likes_path(post.id),method: :post,remote: true do %> 
     <i class="fa fa-heart like-btn fa-2x"></i> 
    <% end %> 
  <% end %>
    <% if post.likes.count != 0 %> 
      <span><%= "#{post.likes.count}いいね!" %></span> 
    <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>"); 

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/edit.html.erb
<%= javascript_pack_tag 'home/preview' %>
<%= render "shared/header" %>
  <% breadcrumb :edit %>
  <div id="container">
  <div class="new-post">
    <%= form_with model: @post, class: 'form', local: true do |f| %>
      <div class="edit-page">
        <h2>Edit Page</h2>
      </div>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="image-post">
        <%= f.file_field :image, class: "file-post" %>
        <div id="image-list"></div>
      </div>
      <div class="caption-post">
        <%= f.text_area :caption, class:"text-post", placeholder:"投稿するアイテムの口コミを書こう!" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="category">
        <p>カテゴリー</p>
      </div>
      <div class="category-post">
        <%=f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"collection-post"}) %>
      </div>
      <div class="post-submit">
        <%= f.submit 'SEND', class: 'submit' %>
      </div>
    <% end %>
  </div>

  <%= render "shared/footer" %>
</div>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div id="container">
  <div class="wrapper">
    <div class="top-wrapper">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :category_id_eq, Category.where.not(id: 1), :id, :name, include_blank: "カテゴリー検索" %> 
        <%= f.submit "検索" %> 
      <% end %>
      <h1>Welcome To KIREI</h1>
      <h1>Make men more beautiful</h1>
      <p>ようこそKIREIへ</p>
      <p>KIREIは男性特化型コスメ情報共有サービスです</p>
      <p>有益な情報を皆様で共有していきましょう</p>
      <% unless user_signed_in? %>
        <p><%= "※各機能を使うためにはログインが必要です"%></p>
      <% end %>  
    </div>
  </div>
  
  <div class="posts">
    <% if @posts.present? %>
      <%= render partial: "shared/post", locals: {post: @posts} %>
    <% else %>
      <p class="no-post">まだ投稿がありません</p>
      <p class="no-post">投稿しよう！</p>
    <% end %>
  </div>

  <div class="page-nation">
    <%= paginate @posts %>
    <%= link_to(new_post_path, class: "purchase-btn") do %>
      <% breadcrumb :root %>
      <span class="purchase-btn-text">投稿する</span>
      <%= image_tag "post-icon.png" , size: "180x50" ,class: "purchase-btn-icon" %>
    <% end %>
    <%= render "shared/footer" %>
  </div>
</div>

app/views/posts/new.html.erb
<%= javascript_pack_tag 'home/preview' %>
<%= render "shared/header" %>
<div id="container">
  <div class="fix"></div>
  <% breadcrumb :new %> 
  <div class="new-post">
    <%= form_with model: @post, class: 'form', local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="image-post">
        <%= f.file_field :image, class: "file-post" %>
        <div id="image-list"></div>
      </div>
      <div class="caption-post">
        <%= f.text_area :caption, class:"text-post", placeholder:"投稿するアイテムの口コミを書こう!" ,rows:"7" ,maxlength:"1000", wrap:"soft" %>
      </div>
      <div class="category">
        <p>カテゴリー</p>
      </div>
      <div class="category-post">
        <%=f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"collection-post"}) %>
      </div>
      <div class="post-submit">
        <%= f.submit 'SEND', class: 'submit' %>
      </div>
    <% end %>
  </div>
    <%= render "shared/footer" %>
</div>

app/views/posts/ranking.html.erb
<%= render "shared/header" %>
<% breadcrumb :ranking %>
<div id="container">
  <div class="rankings">
    <h1 class="ranking-logo">いいね！ランキング</h1>
    <div class="ranking-post">
      <% if @posts[0].present? %>
        <div class="top-ranking-post">
          <p>いいね！数ランキング １位</p>
          <%= link_to "投稿者 #{@posts[0].user.nickname}", user_path(@posts[0].user.id), class:"user-name-ranking" %>
          <span class="ranking-time"><%= l @posts[0].created_at %></span>
        </div>
        <div class="main-ranking-post">
          <%= image_tag "icon_ranking_s_01.png" , size: "90x90" ,class: "ranking-icon" %> 
          <%= link_to(post_path(@posts[0].id),class:"link-ranking") do %>
            <%= image_tag @posts[0].image, class: 'image-ranking-post' %> 
          <% end %>
        </div>
        <div class="footer-ranking-post">
          <div id="likes_buttons_<%= @posts[0].id %>">
           <%= render partial: "likes/like", locals: {post: @posts[0]} %> 
          </div>
          <hr>
          <div class="caption-area">
            <p class="caption"><%= @posts[0].caption %></p>
          </div>
          <hr>
          <p><%= "アイテムカテゴリー : #{@posts[0].category.name}"%></p>
        </div>
      <% end %>
    </div>
    <div class="ranking-post">
      <% if @posts[1].present? %>
        <div class="top-ranking-post">
          <p>いいね！数ランキング 2位</p>
          <%= link_to "投稿者 #{@posts[1].user.nickname}", user_path(@posts[1].user.id), class:"user-name-ranking" %>
          <span class="ranking-time"><%= l @posts[0].created_at %></span>
        </div>
        <div class="main-ranking-post">
          <%= image_tag "icon_ranking_s_02.png" , size: "90x90" ,class: "ranking-icon" %>
          <%= link_to(post_path(@posts[1].id),class:"link-ranking") do %>
            <%= image_tag @posts[1].image, class: 'image-ranking-post' %> 
          <% end %>
        </div>
        <div class="footer-ranking-post">
          <div id="likes_buttons_<%= @posts[1].id %>">
           <%= render partial: "likes/like", locals: {post: @posts[1]} %> 
          </div>
          <hr>
          <div class="caption-area">
            <p class="caption"><%= @posts[1].caption %></p>
          </div>
          <hr>
          <p><%= "アイテムカテゴリー : #{@posts[1].category.name}"%></p>
        </div>
      <% end %>
    </div>
    <div class="ranking-post">
      <% if @posts[2].present? %>
        <div class="top-ranking-post">
          <p>いいね！数ランキング 3位</p>
          <%= link_to "投稿者 #{@posts[2].user.nickname}", user_path(@posts[2].user.id), class:"user-name-ranking" %>
          <span class="ranking-time"><%= l @posts[2].created_at %></span>
        </div>
        <div class="main-ranking-post">
          <%= image_tag "icon_ranking_s_03.png" , size: "90x90" ,class: "ranking-icon" %>
          <%= link_to(post_path(@posts[2].id),class:"link-ranking") do %>
            <%= image_tag @posts[2].image, class: 'image-ranking-post' %> 
          <% end %>
        </div>
        <div class="footer-ranking-post">
          <div id="likes_buttons_<%= @posts[2].id %>">
           <%= render partial: "likes/like", locals: {post: @posts[2]} %> 
          </div>
          <hr>
          <div class="caption-area">
            <p class="caption"><%= @posts[2].caption %></p>
          </div>
          <hr>
          <p><%= "アイテムカテゴリー : #{@posts[2].category.name}"%></p>
        </div>
      <% end %>
    </div>
      <% unless @posts.present? %>
        <h1 class="no-post">いいね！された投稿がないのでランキングは表示されません<h1>
      <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/search.html.erb
<%= render "shared/header" %>
<div id="container">
  <div class="wrapper">
    <div class="top-wrapper">
      <%= search_form_for @p, url: search_posts_path, class: "search-form" do |f| %>
        <%= f.collection_select :category_id_eq, Category.where.not(id: 1), :id, :name, include_blank: "カテゴリー検索", class: "search-select" %> 
        <%= f.submit "検索", class: "searc-submit" %> 
      <% end %>
      <h1>Welcome To KIREI</h1>
      <h1>Make men more beautiful</h1>
      <p>ようこそKIREIへ</p>
      <p>KIREIは男性特化型コスメ情報共有サービスです</p>
      <p>有益な情報を皆様で共有していきましょう</p>
      <% unless user_signed_in? %>
        <p><%= "※各機能を使うためにはログインが必要です"%></p>
      <% end %> 
    </div>
  </div>

  <div class="posts">
    <%= render partial: "shared/post", locals: {post: @posts} %>
  </div>
  
  <div class="page-nation">
    <%= paginate @posts %>
    <%= link_to(new_post_path, class: "purchase-btn") do %>
      <% breadcrumb :root %>
      <span class="purchase-btn-text">投稿する</span>
      <%= image_tag "post-icon.png" , size: "180x50" ,class: "purchase-btn-icon" %>
    <% end %>
    <%= render "shared/footer" %>
  </div>
</div>

app/views/posts/show.html.erb
<%= javascript_pack_tag 'home/comment' %>
  <%= render "shared/header" %>
<div id="container">
  <% breadcrumb :show %>
  <div class="show-posts">  
    <div class="show-post">
      <div class="top-show">
        <%= link_to "投稿者 #{@post.user.nickname}", user_path(@post.user.id), class:"user-name-post" %>
        <span><%= l @post.created_at %></span>
      </div>
      <div class="main-show">
        <div class="trash-edit">
          <% if user_signed_in? && current_user.id == @post.user_id %>
            <div class="trash">
              <%= link_to(post_path(@post.id), method: :delete, class:"fa fa-trash fa-3x trash-btn", style: "display: flex;", data: { confirm: "本当に削除しますか？" } ) do%>
              <% end %>
            </div>
            <div class="edit">
              <%= link_to(edit_post_path(@post.id),class:"fa fa-edit fa-3x edit-btn",style: "display: flex;") do %>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= link_to(post_path(@post.id),class: "show-link") do %>
          <%= image_tag @post.image, class: 'image-main-show' %> 
        <% end %>
      </div>
      <div class="footer-show">
        <div id="likes_buttons_<%= @post.id %>">
          <%= render partial: "likes/like",locals: {post: @post} %>
        </div>
        <hr>
        <div class="caption-area">
          <p class="caption"><%=safe_join(@post.caption.split("\n"),tag(:br))%></p>
        </div>
        <hr>
        <p><%= "アイテムカテゴリー : #{@post.category.name}"%></p>
      </div>
    </div>

  <% if user_signed_in? %>
    <div class="comments">
      <div class="comment">
        <% if user_signed_in? %>
          <%= form_with(model: [@post, @comment], local: true, class:"comment-form",id:"form") do |form| %>
            <%= form.text_area :text, placeholder: "コメントを追加...",class:"comment-area", row: "1", id:"text" %>
            <%= form.submit "コメント",class:"comment-submit",id:"submit" %>
          <% end %>
        <% end %>
      </div>
      <% if @comments.present? %>
        <p class="comment-count" id="comment-count"><%= "コメント#{@comments.count}件全てを表示" %></p>
      <% end %>
    </div>
  <% else %>
    <p class="no-comment">＊ログイン済みのユーザーのみコメントができます</p>
  <% end %>
  <div id="list">
  </div>
<div class="comments-area">
  <% @comments.each do |comment| %>
    <div id="trash_btn_<%= comment.id%>">
      <div class="comment-dates">
        <div class="comment-text" id="comment-text">
            <%= render partial: "comments/comment",locals: {comment: comment} %>
        </div>
        <hr>
      </div>
    </div>
  <% end %>
</div>
</div>
<%= render "shared/footer" %>

app/views/rooms/index.html.erb
<%= render "shared/header" %>
<div id="container">
<% breadcrumb :room %> 
  <div class=chats>
    <h1 class="chat-logo">チャット履歴</h1>
    <hr class="line">
    <div class="chats-user">
      <ul>
        <% @users.each do |user| %>
        <div class="chats-users-list">
          <%= link_to user_path(user.id) do %>
            <li class="chat-user-list"><%= user.nickname%><li>
          <% end %>
          <li>
            <%= link_to "チャット", room_path(user.room_ids),class:"chat-btn" %>
          </li>
        </div>
        <hr>
        <% end %>
      </ul>
    </div>
  </div>
<div class="fix">
  <%= render "shared/footer" %>
</div>
</div>

app/views/rooms/show.html.erb
<%= render "shared/header" %>
<div id="container">
  <% breadcrumb :mychat %>
  <% breadcrumb :chat %>
  <div class="chat-room" id="chat-room" data-user-id="<%= current_user.id %>">
    <p class=chat-member>チャットメンバー</p>
    <div class="chat-user-names">
      <% @entries.each do |e| %>
        <div class="chat-user-name" >
          <%= link_to "・#{e.user.nickname}", user_path(e.user_id) %>
        </div>
      <% end %>
    </div>
    <hr>
      <div class="chat">
        <div id="message-list">
          <% if @messages.present? %>
            <div class="message-list">
              <% @messages.each do |m| %>
                <div class="chat-hukidashi <%= current_user.id == m.user_id ? "mycomment" : "another"%>">
                  <div class="current-message-time" > 
                    <span class="time"><%= l m.created_at %></span>
                    <span class="current-message"><%=safe_join(m.message.split("\n"),tag(:br))%></span>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <hr>
      <div class="messages-form">
        <%= form_with model: @message, class: "message-form", id: "form" do |f| %>
          <%= f.text_area :message, placeholder: 'メッセージ...' , class:"form-text-field", id:"message-form", maxlength:"100", wrap:"soft" %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "送信",class: 'form-submit', id: "submit" %>
        <% end %>
      </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/users/followers.html.erb
<%= render "shared/header" %>
<div id="container">
  <% breadcrumb :follower %>
  <div class=follows>
    <h1 class="follows-log">Follower</h1>
    <hr class="line">
    <%= render "shared/follow" %>
  </div>
  <div class="fix">
    <%= render "shared/footer" %>
  </div>
</div>

app/views/users/followings.html.erb
<%= render "shared/header" %>
<div id="container">
  <% breadcrumb :following %>
  <div class=follows>
    <h1 class="follows-log">Following</h1>
    <hr class="line">
    <%= render "shared/follow" %>
  </div>
  <div class="fix">
    <%= render "shared/footer" %>
  </div>
</div>

app/views/users/likes.html.erb
<%= render "shared/myheader" %>
<div id="container">
  <% breadcrumb :user %>
  <div class="mypage-posts">
    <div class="mypage-container">
      <div class="direct-message">
        <% if current_user == @user %>
          <%= link_to(rooms_path,class:"fa fa-envelope fa-3x message-btn",style: "display: flex;" ) do%>
          <% end %>
        <% end %>
        <% unless @user.id == current_user.id %>
          <%# <% if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %> 
          <% if @is_room == true %>
            <%= link_to "チャット", room_path(@room_id),class:"user-show-chat" %>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "チャット", class:"btn btn-primary btn-lg user-show-chat"%>
            <% end %>
          <% end %>
          <%# <% end %> 
        <% end %>
        <span class="mypage-logo">MyPage</span>  
      </div>
      <div class="mypage-follow">
        <div id="follow_button_<%= @user.id %>">
          <%= render partial: "relationships/followcount", locals: {user: @user} %>
        </div>
      </div>
      <hr>
      <div class="posts-or-likes">
        <%= link_to "投稿", user_path(@user.id), class: "like-posts" %>
        <span class="like-likes">いいね！</span>
      </div>
    </div>
    <div class="mypage-post">
      <% if @like_posts.present? %>
        <% @like_posts.each do |post| %>
          <%= render partial: "shared/mypage", locals: {post: post} %>
        <% end %>
      <% else %>
        <P class="no-mypage-post"><%= "#{@user.nickname}さんがいいね！した投稿はありません" %></P>
      <% end %>
    </div>
    <div class="mypage-nation">
      <%= paginate @like_posts %>
    </div> 
  </div>
</div>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/myheader" %>
<div id="container">
  <% breadcrumb :user %>
  <div class="mypage-posts">
    <div class="mypage-container">
      <div class="direct-message">
        <% if current_user == @user %>
          <%= link_to(rooms_path,class:"fa fa-envelope fa-3x message-btn",style: "display: flex;" ) do%>
          <% end %>
        <% end %>
        <% unless @user.id == current_user.id %>
          <%# 相互フォローの時チャットボタンが表示されるコード、テスト時の簡略化のためコメントアウトにしてあります %>
          <%# <% if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %> 
          <% if @is_room == true %>
            <%= link_to "チャット", room_path(@room_id),class:"user-show-chat" %>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "チャット", class:"btn btn-primary btn-lg user-show-chat", data: { confirm: "ルームを新規作成しチャットをしますか？" }%>
            <% end %>
          <% end %>
          <%# <% end %> 
        <% end %>
        <h1 class="mypage-logo">MyPage</h1>
      </div>
      <div class="mypage-follow">
        <div id="follow_button_<%= @user.id %>">
          <%= render partial: "relationships/followcount", locals: {user: @user} %>
        </div>
      </div>
      <hr>
      <div class="posts-or-likes">
        <span class="my-posts">投稿</span>
        <%= link_to "いいね！", likes_user_path(@user.id), class: "my-likes" %>
      </div>
    </div>
    <div class="mypage-post">
      <% if @posts.present? %>
        <% @posts.each do |post| %>
          <%= render partial: "shared/mypage", locals: {post: post} %>
        <% end %>
      <% else %>
        <p class="no-mypage-post"><%= "#{@user.nickname}さんの投稿はまだありません" %></p>
      <% end %>
    </div>
      <div class="mypage-nation">
        <%= paginate @posts %>
      </div>
  </div>
</div>
<%= render "shared/footer" %> 