config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    get :ranking, on: :collection
    get :search, on: :collection
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get :likes, on: :member
  end
  resources :messages, only: :create
  resources :rooms, only: [:index, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '洗顔料'},
    {id: 3, name: 'クレンジング'},
    {id: 4, name: '化粧水'},
    {id: 5, name: '乳液、美容液'},
    {id: 6, name: 'フェイスクリーム'},
    {id: 7, name: '日焼け対策、UVケア'},
    {id: 8, name: 'ベースメイク'},
    {id: 9, name: '香水、フレグランス'},
    {id: 10, name: 'ヘアケア、スタイリング'},
    {id: 11, name: '美容グッズ、美容家電'},
    {id: 12, name: 'サプリメント、フード'},
    {id: 13, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    # {id: 1, name: '---'},
    {id: 2, name: '男性'},
    {id: 3, name: '女性'}
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :caption
    validates :image
    validates :category_id, numericality: {other_than: 1, message: "を選択してください"}
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

  has_many :posts
  has_many :comments
  has_many :likes
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :message, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  

  with_options presence: true do
    validates :nickname
    validates :age, format: {with: /\A[0-9]{2,3}\z/, message: "は半角数字で入力してください"}
    validates :gender_id
  end
  validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は6文字以上、半角英数混合で入力してください"}
  
  def liked_by?(post)
    self.likes.exists?(post_id: post.id)
  end

  def followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def destroy
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
  end

  private 
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :back_index, only: :edit
  before_action :search_item_category

  def index
    @posts = Post.order("created_at DESC").page(params[:page]).per(9)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy 
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    @posts = @p.result.order("created_at DESC").page(params[:page]).per(2)
    category_id = params[:q][:category_id_eq]
    @category = Category.find_by(id: category_id)
  end

  def ranking
    @posts = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
  
  private 
  def post_params
    params.require(:post).permit(:image,:caption,:category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def back_index
    if current_user.id != @post.user_id
      redirect_to root_path
    end
  end

  def search_item_category
    @p = Post.ransack(params[:q])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>KireiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Caveat">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
  </head>

  <body>
        <%= breadcrumbs separator: " &rsaquo; " %>
        <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<div class="follows-user">
  <ul>
    <% @users.each do |user| %>
    <div class="follows-user-list">
      <%= link_to user_path(user) do %>
        <li class="user-list"><%= user.nickname%><li>
      <% end %>
      <li>
        <div id="follows_buttons_<%= user.id %>">
          <%= render partial: "relationships/relationship", locals: {user: user} %>
        </div>
      </li>
    </div>
    <hr>
    <% end %>
  </ul>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>Copyright © KIREI All Rights Reserved.</p>
</footer>

app/views/shared/_header.html.erb
<%= javascript_pack_tag 'home/hunberger' %>
<header>  
  <div class="header-top">
    <%= image_tag "menu.png" , size: "50x50" ,class: "menu-icon", id: "menu" %>  
      <div class="menu-list">
        <ul class="menus">
          <li><%= link_to "KIREI", root_path, class: "hum-kirei", style: "color: black;" %></li>
          <li><%= link_to "Ranking", ranking_posts_path, class: "hum-ranking", style: "color: black;" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "MyPage", user_path(current_user.id), class: "hum-my-page", style: "color: black;" %></li> 
            <li><%= link_to "LogOut", destroy_user_session_path,  method: :delete, class: "hum-logout", style: "color: black;" %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path, class: "hum-login", style: "color: black;" %></li>
            <li><%= link_to "SignUp", new_user_registration_path, class: "hum-signup", style: "color: black;" %></li>
          <% end %>
        </ul>
      </div> 
    <div class="header-left">
      <%= link_to "KIREI", root_path, class: "kirei" %>
      <%= link_to "Ranking", ranking_posts_path, class: "ranking" %>
    </div>
    <div class="header-right">
      <% if user_signed_in? %>
        <%= link_to "MyPage", user_path(current_user.id), class: "my-page" %>
        <%= link_to 'LogOut', destroy_user_session_path, method: :delete, class: "logout" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "login" %>
        <%= link_to "SignUp", new_user_registration_path, class: "sign-up" %>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_myheader.html.erb
<%= javascript_pack_tag 'home/hunberger' %>
<header>  
  <div class="header-top">
    <%= image_tag "menu.png" , size: "50x50" ,class: "menu-icon", id: "menu" %>  
      <div class="menu-list">
        <ul class="menus">
          <li><%= link_to "KIREI", root_path, class: "hum-kirei", style: "color: black;" %></li>
          <li><%= link_to "Ranking", ranking_posts_path, class: "hum-ranking", style: "color: black;" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "MyPage", user_path(current_user.id), class: "hum-my-page", style: "color: black;" %></li> 
            <li><%= link_to "LogOut", destroy_user_session_path,  method: :delete, class: "hum-logout", style: "color: black;" %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path, class: "hum-login", style: "color: black;" %></li>
            <li><%= link_to "SignUp", new_user_registration_path, class: "hum-signup", style: "color: black;" %></li>
          <% end %>
            <li>
              <% unless @user.id == current_user.id %> 
                <%# <% if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %> 
                <% if @is_room == true %> 
                  <%= link_to "Chat", room_path(@room_id),class:"hum-user-show-chat", style: "color: black;" %>
                <% else %> 
                  <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e| %> 
                      <%= e.hidden_field :user_id, value: @user.id %> 
                    <% end %> 
                    <%= f.submit "Chat", class:"btn btn-primary btn-lg hum-user-show-chat", style: "color: black;" %> 
                  <% end %> 
                <% end %> 
                <%# <% end %> 
              <% end %>  
            </li>
        </ul>
      </div> 
    <div class="header-left">
      <%= link_to "KIREI", root_path, class: "kirei" %>
      <%= link_to "Ranking", ranking_posts_path, class: "ranking" %>
    </div>
    <div class="header-right">
      <% if user_signed_in? %>
        <%= link_to "MyPage", user_path(current_user.id), class: "my-page" %>
        <%= link_to 'LogOut', destroy_user_session_path, method: :delete, class: "logout" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "login" %>
        <%= link_to "SignUp", new_user_registration_path, class: "sign-up" %>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_mypage.html.erb
<div class="post">
  <div class="top-post">
    <%= link_to "投稿者 #{post.user.nickname}", user_path(post.user.id), class:"user-name-post" %>
    <span><%= l post.created_at %></span>
  </div>
  <div class="main-post">
    <%= link_to(post_path(post.id),class:"link-image") do %>
    <%= image_tag post.image, class: 'image-main-post' %> 
    <% end %> 
  </div>
  <div class="footer-post">
    <div id="likes_buttons_<%= post.id %>">
      <%= render partial: "likes/like", locals: {post: post} %>
    </div>
    <hr>
    <div class="caption-area">
      <p><%=safe_join(post.caption.split("\n"),tag(:br))%></p>
    </div>
    <hr>
    <p><%= "アイテムカテゴリー : #{post.category.name}"%></p>
  </div>
</div>

app/views/shared/_post.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <div class="top-post">
      <%= link_to "投稿者 #{post.user.nickname}", user_path(post.user.id), class:"user-name-post" %>
      <span><%= l post.created_at %></span>
    </div>
    <div class="main-post">
      <%= link_to(post_path(post.id),class:"link-image") do %>
        <%= image_tag post.image, class: 'image-main-post' %> 
      <% end %>
    </div>
    <div class="footer-post">
      <div id="likes_buttons_<%= post.id %>">
        <%= render partial: "likes/like", locals: {post: post} %>
      </div>
      <hr>
      <div class="caption-area">
        <p class="caption"><%=safe_join(post.caption.split("\n"),tag(:br))%></p>
      </div>
      <hr>
      <p><%= "アイテムカテゴリー : #{post.category.name}"%></p>
    </div>
  </div>
<% end %>